# Generated by Django 5.2.1 on 2026-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_notes_patient_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
