# Generated by Django 5.2.16 on 2026-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_first_name_alter_patient_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("uz", "O'zbek")],
                default="ru",
                max_length=2,
            ),
        ),
    ]
