# Generated by Django 5.2.16 on 2026-07-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "sms_type",
                    models.CharField(
                        choices=[
                            ("registration", "Подтверждение записи"),
                            ("reminder", "Напоминание о приеме"),
                            ("birthday", "Поздравление с днем рождения"),
                            ("general", "Общее сообщение"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("waiting", "В обработке"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "eskiz_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал SMS",
                "verbose_name_plural": "Журнал SMS",
                "ordering": ["-created_at"],
            },
        ),
    ]
