# Generated by Django 6.0.5 on 2026-05-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_treatmentplan_treatmentplanitem_servicematerialnorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('ARRIVED', 'Arrived'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], db_index=True, default='BOOKED', max_length=20),
        ),
    ]
