# Generated by Django 6.0.5 on 2026-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
