# Generated by Django 5.2.16 on 2026-07-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointment_custom_price_and_more"),
        ("finance", "0002_transaction_is_voided"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="appointments.appointment",
            ),
        ),
    ]
