# Generated by Django 5.2.1 on 2026-05-19 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('ANESTHESIA', 'Анестезия'), ('FILLINGS', 'Пломбы'), ('INSTRUMENTS', 'Инструменты'), ('IMPLANTS', 'Импланты'), ('OTHER', 'Прочее')], default='OTHER', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(default='шт', max_length=20)),
                ('min_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('log_type', models.CharField(choices=[('RESTOCK', 'Пополнение'), ('CONSUMPTION', 'Расход'), ('EXPIRY', 'Списание (просрочено)'), ('ADJUSTMENT', 'Корректировка')], default='CONSUMPTION', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_logs', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.material')),
            ],
        ),
    ]
