# Generated by Django 6.0.5 on 2026-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Срок годности материала', null=True),
        ),
    ]
